### ISSUE TITLE
Config redesign

### ISSUE THREAD

**Issue by thinkingfish** [twitter/rpc-perf#168]
Given size/num are now set for 4 different parameters, I wonder if it makes sense to reconsider how workload is specified- explicitly, does it make sense to create separate section about the dataset (key space, key generation scheme, value size etc), and load (rate, arrival pattern for the future). @brayniac what do you think?

_Originally posted by @thinkingfish in https://github.com/twitter/rpc-perf/pull/167_

**Comment by thinkingfish** [comment]
Other thoughts on this topic from #167 

https://github.com/twitter/rpc-perf/pull/167#discussion_r238887044
https://github.com/twitter/rpc-perf/pull/167#discussion_r239987958
https://github.com/twitter/rpc-perf/pull/167#discussion_r239988114
https://github.com/twitter/rpc-perf/pull/167#discussion_r239988736

**Comment by brayniac** [comment]
The 3.0.0-pre code has been landed to master and implements a redesign of the configuration. This should make it easier to describe more complex workloads in terms of probability for key space and value sizes. Rate is separated out to make it easy to test with the same dataset at different load levels.
