### ISSUE TITLE
network interface binding on client

### ISSUE THREAD

**Issue by HarpPDX** [twitter/rpc-perf#170]
On client systems that have multiple NICs/IP addresses, it would be useful to be able to specify which local interface (either ip address or interface name, e.g. eth0) to use for the connection to the server.

An example...I have a 10Gb NIC and a 25Gb NIC on my client system. It is not clear which will be used by rpc-perf.

**Comment by brayniac** [comment]
rpc-perf currently uses `connect()` to open a TCP stream to the server. As-such, it's left up to the kernel to decide on what source address and port to use for the connection. This would follow the routing table on your client system for the address specified to the `--server [ip:port]` option to rpc-perf.

While it might be possible to do "bind before connect", this appears to be pretty uncommon and comes with some increased complexity in managing the sockets. Such a change would be deferred to 3.0.0+. I am currently reworking a significant portion of the networking code within rpc-perf, this change would be easier to accommodate in the reworked code.

In the meantime, you should be able to determine the behavior by consulting the routing table on your client system or by observing the established connections while rpc-perf is running.
