### ISSUE TITLE
Mio

### ISSUE THREAD

**Issue by jnicholls** [twitter/rpc-perf#23]
Why did you include mio source into the rpc-perf repo instead of using a version from crates.io or linking directly to its git repo?  Just curious :)

**Comment by brayniac** [comment]
@jnicholls great question. This was initially done to have some control around the dependencies mio was pulling in. Initially it was just for `bytes`, but if you look now, `libc` and `nix` dependencies for mio are also customized so rpc-perf could be run on aarch64.

I'm hoping this goes away once rpc-perf is on mio 0.5.x, but until we're there I'll leave this open.
