### ISSUE TITLE
Warmup rate exceeds configured rate

### ISSUE THREAD

**Issue by mahakp** [twitter/rpc-perf#46]
While testing using thrift protocol, we discovered that rpc-perf doesnot respect the rate param specified in config file

**Comment by brayniac** [comment]
This is a valid bug. Currently the workload generator initializes a token bucket ratelimiter with a fixed bucket capacity of 10_000. This will result in non-ratelimited behavior during the warmup. This is a non-obvious behavior and should be fixed.

**Comment by brayniac** [comment]
brayniac/ratelimit#8 is the root issue. Once the fix is merged and the crate republished, we will update to the new version of ratelimit to pickup the fix.
