### ISSUE TITLE
workload::Value and request::thrift::ThriftValue are almost identical

### ISSUE THREAD

**Issue by bryce-anderson** [twitter/rpc-perf#72]
Something I've run into hacking on #64 is that the [workload::Value](https://github.com/twitter/rpc-perf/blob/master/lib/workload/src/lib.rs#L116) enum and [request::thrift::ThriftValue](https://github.com/twitter/rpc-perf/blob/master/lib/request/src/thrift.rs#L34) enum are nearly identical. This results in tree translation [here](https://github.com/twitter/rpc-perf/blob/master/lib/workload/src/lib.rs#L358). By using the same tree structure the copy could be avoided. I'm suggesting making `Parameter` and `Value` the 'tree to rule them all' which can be directly used by things like `thrift` for generating a buffer. IMO this makes sense because all the information harvested from the config parsing should be available in this tree, rendering everything else strictly a subset.

A complication is that the build is split out in such a way that `rpcperf_workload` depends on `rpcperf_request` but the tree is defined in `rpcperf_workload` and it results in a cyclic dependency when trying to expose this tree to both modules. Two possible solutions for this are to make yet another module just for that tree or merge rpcperf_workload and rpcperf_request modules. The workload module is a single file so I think merging them is the easiest thing to do.

On the other hand, maybe this is not a good idea altogether for reasons I've not yet contemplated.

**Comment by brayniac** [comment]
Yeah, this was one of the annoying things about the changes for generic thrift support. I think the suggestion to have 'one tree to rule them all' is exactly what is needed here. There is no knowledge beyond what is in the config, which is would be represented in the tree. 

Let me have some more coffee and ponder further. I'm thinking that the existing split between workload and request are fairly artificial anyway, and given what is required to support #64 that line becomes blurred even further.

**Comment by bryce-anderson** [comment]
Cool. It becomes very obvious when trying to make the tree recursive for #64: translation becomes annoying (doable, just it becomes more obviously redundant). I was in the process of doing the merger and thought I should float the idea before wasting my time.

I'm happy to tackle this sometime in the next few days (in fact I'm already most of they way there) if it's the way forward.

**Comment by brayniac** [comment]
I think you're absolutely right here. I still can't come up with any reasons against. I suspect there'll be benefits for even handling something basic like memcache protocol, where currently the TTL is hard-coded to `None`, but it's something I'd like to be able to specify in the config to help balance between expiry and eviction. 

Let's move forward with your proposal.
