### ISSUE TITLE
Can the different protocols be modularized

### ISSUE THREAD

**Issue by bryce-anderson** [twitter/rpc-perf#78]
Currently the details of each protocol leak into many areas that shouldn't really care such as [connection management](https://github.com/twitter/rpc-perf/blob/b14087e71cf9d4a128d64f358d338dc703d6c086/src/connection.rs#L169) and [workload buffer generation](https://github.com/twitter/rpc-perf/blob/b14087e71cf9d4a128d64f358d338dc703d6c086/lib/workload/src/lib.rs#L282). An example of this tight coupling leading to problems when generating a workload can be found [here](https://github.com/twitter/rpc-perf/blob/b14087e71cf9d4a128d64f358d338dc703d6c086/lib/workload/src/lib.rs#L207): each protocol needs to be concerned with types that it probably has no notion of.

I propose changing the structure. A protocol needs to do these things:
* parse its config 
* Generate a workload buffer
* Parse the response

This can be balled up into a `trait` with the relatively simple interface:
```rust
trait Protocol {
    fn generate_request(&mut self) -> Vec<u8>;
    fn parse_response(&mut self, bytes: &[u8]) -> ParsedResponse;
}

mod thrift {
   fn parse_config(config: Toml) -> Box<Protocol> // Could also give a concrete type and box later...
}
```

From there, each module will implement its own protocol specific parsing, types, etc. This moves the coupling of the protocols to only a single point: the initialization of the parsing when a protocol must be selected.

Benefits include:
* Stronger static guarantees about each individual protocol
* Easier testing of individual protocols
* Easier to implement new protocols.
* This will make mux support easier because protocols could be transparently stacked.

**Comment by brayniac** [comment]
I like the proposal. I'm curious about how this interacts with mixed workloads. Can you go into more detail on that aspect?

**Comment by bryce-anderson** [comment]
To a first approximation it should work the same way it does now: the workloads will churn out data and the connection will delegate to the `Protocol` `trait` for parsing instead of matching on an `enum`. 

However, after doing some digging, I think the current workload model is incompatible with session layer protocols such as mux, or more specifically, any protocol that requires some notion of a connection state. Currently the workload generators push message buffers to a queue and which connection gets them is undefined. For mux this won't work because each message will get an associated id so the workload generator would need to know which id's are in use on that connection. The solution to this is to generate work on a connection basis and instead of sharing a work queue with all the connections, share the rate management state. Considering everything is being generated synchronously this could be done on the mio reactor threads without much worry. Unfortunately that would be another large change. On the bright side, it would actually significantly simplify some parts of this issue.

**Comment by brayniac** [comment]
I'm a little hesitant to place this into the mio reactor threads. I had settled on this particular design after having an implementation that generated work within a connection. I was not happy with that design. That said, I'm happy to leave this to a benchmark to dictate the decision here.

**Comment by bryce-anderson** [comment]
I think changing the thread structure would be for a different PR. I'd like to go about doing this one as best as possible and that will help facilitate experimenting with the thread model. That will require the traits above to be modified a bit: instead of a single trait they become two traits: a generator and receiver. 
```rust
trait ProtocolGen {
    fn gen_message(&mut self) -> Vec<u8>;
}

trait ProtocolParse {
    fn parse_message(&mut self, data: &[u8]) -> ParsedResponse;
}

mod thrift {
   fn parse_config(config: Toml) -> (Box<ProtocolGen>,  Box<ProtocolParse>) { ... }
}
```
If the thread model converges such that the messages are generated on a per-connection basis then the two protocol traits could be merged.

**Comment by brayniac** [comment]
Sounds good. Let's start with the traits. I'll see if I can prioritize adding some stats and benchmarks for various components. Those will help us in making measured decisions.
